### ISSUE TITLE
[Find in current tab] button doesn't work for certain file name tabs.

### ISSUE THREAD

**Issue by jackusay** [jackusay/cuda_find_in_filesJ#16]
filename: csdf (1).md

**Comment by jackusay** [comment]
This is a bug in the upstream FinF 4.8.12.

**Comment by Alexey-T** [comment]
Reported this bug to the main repo.

**Comment by jackusay** [comment]
https://github.com/kvichans/cuda_find_in_files4/issues/88

**Comment by jackusay** [comment]
fixed https://github.com/jackusay/cuda_find_in_filesJ/commit/cd6bf189b8fc1d36eb53eeb80e762bf0ad352043
